---
- name: Change user's password for linux
  hosts: all
  gather_facts: no
  vars: 
    username: masterjin77
    password: "{{ 'wk0025' | password_hash('sha512') }}"
 
  tasks: 
    - name: Change "{{ username }}" password
      user:
        name: "{{ username }}"
        update_password: always 
        password: "{{ password }}"